# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: azure-job

trigger:
- main

jobs:
-  job: "job-1"
   pool:
    vmImage: ubuntu-latest
   steps:
   - script: echo Hello, world!
     displayName: 'Hello-world-step'

   - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
     displayName: 'Second-step'
-  job: "job-2"
   pool:
    vmImage: ubuntu-latest
   steps:
   - script: echo Goodbye!
     displayName: 'Goodbye-step'